//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasVidaWebMVC
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Audit
    {
        [Key]
        public int AuditID { get; set; }
        public string AuditDescription { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<System.DateTime> AuditDateTime { get; set; }
    
        public virtual User User { get; set; }
    }
}
