//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasVidaWebMVC
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class TransactionType
    {
        public TransactionType()
        {
            this.Transactions = new HashSet<Transaction>();
        }

        [Key]
        public int TransactionTypeID { get; set; }

        [DisplayName("Nombre")]
        public string TransactionTypeName { get; set; }

        [DisplayName("Descripcion")]
        public string TransactionTypeDescription { get; set; }
    
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
