//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCGA.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistorialAfiliado
    {
        public int Id { get; set; }
        public int afiliado_id { get; set; }
        public System.DateTime fecha { get; set; }
        public int plan_activo { get; set; }
        public string motivo_cambio { get; set; }
        public System.DateTime createdon { get; set; }
        public string createdby { get; set; }
        public System.DateTime changedon { get; set; }
        public Nullable<int> changedby { get; set; }
    
        public virtual Afiliado Afiliado { get; set; }
        public virtual Plan Plan { get; set; }
    }
}
