//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCGA.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Turno
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Turno()
        {
            this.Atencion = new HashSet<Atencion>();
            this.Cancelacion = new HashSet<Cancelacion>();
        }
    
        public int Id { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.TimeSpan Hora { get; set; }
        public int AfiliadoId { get; set; }
        public int EspecialidadProfesionalId { get; set; }
        public int reserva { get; set; }
        public string Observaciones { get; set; }
        public System.DateTime createdon { get; set; }
        public string createdby { get; set; }
        public System.DateTime changedon { get; set; }
        public string changedby { get; set; }
        public Nullable<System.DateTime> deletedon { get; set; }
        public string deletedby { get; set; }
        public bool isdeleted { get; set; }
    
        public virtual Afiliado Afiliado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Atencion> Atencion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cancelacion> Cancelacion { get; set; }
        public virtual EspecialidadesProfesional EspecialidadesProfesional { get; set; }
        public virtual TipoReseva TipoReseva { get; set; }
    }
}
