//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasVidaWebMVC
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class FamilyGroup
    {
        public FamilyGroup()
        {
            this.Users = new HashSet<User>();
        }

        [Key]
        public int FamilyGroupID { get; set; }

        [DisplayName("Grupo Familiar")]
        public string FamilyName { get; set; }
    
        public virtual ICollection<User> Users { get; set; }
    }
}
