//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasVidaWebMVC
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Product
    {
        public Product()
        {
            this.Transactions = new HashSet<Transaction>();
            this.Users = new HashSet<User>();
        }

        [Key]
        public int ProductID { get; set; }

        [DisplayName("Producto")]
        public string ProductName { get; set; }

        [DisplayName("Descripcion")]
        [DataType(DataType.MultilineText)]
        public string ProductDescription { get; set; }

        [DisplayName("Precio")]
        public double ProductPrice { get; set; }

        [DisplayName("Activo")]
        public bool IsActive { get; set; }
    
        public virtual ICollection<Transaction> Transactions { get; set; }
        public virtual ICollection<User> Users { get; set; }
    }
}
