//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasVidaWebMVC
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Transaction
    {
        [Key]
        public int TransactionID { get; set; }

        [DisplayName("Producto")]
        public string ProductName { get; set; }

        [DisplayName("Precio")]
        public double ProductPrice { get; set; }

        [DisplayName("Fecha de Creacion")]
        public System.DateTime TransactionCreationDate { get; set; }

        [DisplayName("Fecha de Pago")]
        public Nullable<System.DateTime> TransactionPaymentDate { get; set; }

        [DisplayName("Pagado")]
        public bool IsPaid { get; set; }

        [DisplayName("Tipo de Transaccion")]
        public int TransactionTypeID { get; set; }

        public int ProductID { get; set; }
        public int UserID { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual TransactionType TransactionType { get; set; }
        public virtual User Users { get; set; }
    }
}
